version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tax-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tax-network

  nginx:
    image: nginx:alpine
    container_name: tax-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - tax-network

  mysql:
    image: mysql:8.0
    container_name: tax-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - tax-network

networks:
  tax-network:
    driver: bridge 